import { Header } from '@/components/Header'
import StyledComponentsRegistry from '@/lib/styled-components/registry'
import type { Metadata } from 'next'
import { Inter, Lexend_Deca } from 'next/font/google'
import { GlobalStyle } from '@/styles/GlobalStyle'
import { Theme } from '@/theme'
import { Footer } from '@/components/Footer'

const inter = Inter({ subsets: ['latin'], variable: '--inter' })
const lexendDeca = Lexend_Deca({ subsets: ['latin'], variable: '--lexend-deca' })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="pt-Br">
      <body className={`${lexendDeca.variable} ${inter.variable}`}>
        <StyledComponentsRegistry>
          <Theme>
            <GlobalStyle />
            <Header />
            {children}
            <Footer />
          </Theme>
        </StyledComponentsRegistry>
      </body>
    </html>
  )
}
